version: "3"
services:
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PWD}
      POSTGRES_DB: workflow_dev

  elixir:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PWD}
      POSTGRES_DB_TEST: ${PSQL_DB_TEST}
      POSTGRES_DB_DEV: ${PSQL_DB}
      POSTGRES_HOST: ${PSQL_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
